name: WAuctionHouse
version: 1.0.0
main: me.wobble.wauctionhouse.WAuctionHouse
api-version: '1.21'
authors: [Wobble]
depend: [Vault]

commands:
  ah:
    description: Main auction command
    usage: /ah
    aliases: [auction]

permissions:
  wobble.auction.admin:
    description: Full admin access to WAuctionHouse
    default: op

  wobble.auction.reload:
    description: Reload WAuctionHouse configuration
    default: op

  wobble.auction.limit.default:
    description: Default auction listing limit
    default: true

  wobble.auction.limit.vip:
    description: VIP auction listing limit
    default: false
